### ISSUE TITLE
Report {REPLACE_WITH_ADDRESS}B62qmjS7zULb6wG83uhHDaTGQqYQGDP6SqB8TpsfzqpD571fhN8MYor

### ISSUE THREAD

**Issue by chenqian0707** [nerdvibe/mina-addresses-blacklist#120]
**Address?**
Replace this text with the address of the scammer.

**Proof/evidence**
Please write down the proof regarding the scammer address. It might be a TX, a website or anything else.

**Comment by nerdvibe** [comment]
Hi @chenqian0707 , this address (B62qmjS7zULb6wG83uhHDaTGQqYQGDP6SqB8TpsfzqpD571fhN8MYor) is already in the list. Thank you for your report 🙏
