### ISSUE TITLE
Report {B62qjaW8ZuieYyCKTVxMFXm787bCs6PSwmFzJmyUeHw8aPvBnRZSQBF}

### ISSUE THREAD

**Issue by vadim7788** [nerdvibe/mina-addresses-blacklist#283]
This address is used to steal from different mina wallets. The scammer first uses B62qnWkFcq6GTKST61PaVZfqmtrLJaoPX7QZcLXEtv7aNkX9S2pVaoi and than sends to B62qjaW8ZuieYyCKTVxMFXm787bCs6PSwmFzJmyUeHw8aPvBnRZSQBF and after that sends to binance where it sells

**Comment by nerdvibe** [comment]
Unfortunately there are not enough proofs to list this address
