### ISSUE TITLE
Report {B62qoV1TzU7GVWvqL8fApj2jQLmA3FA1U4GznxLWpthzkekAE4NzCE8}

### ISSUE THREAD

**Issue by TamerlanBakirov** [nerdvibe/mina-addresses-blacklist#284]
**Address?**
Replace this text with the address of the scammer.

**Proof/evidence**
Please write down the proof regarding the scammer address. It might be a TX, a website or anything else.

**Comment by nerdvibe** [comment]
Duplicated https://github.com/nerdvibe/mina-addresses-blacklist/issues/285
