### ISSUE TITLE
Report {B62qoV1TzU7GVWvqL8fApj2jQLmA3FA1U4GznxLWpthzkekAE4NzCE8}

### ISSUE THREAD

**Issue by TamerlanBakirov** [nerdvibe/mina-addresses-blacklist#285]
**Address?**
B62qoV1TzU7GVWvqL8fApj2jQLmA3FA1U4GznxLWpthzkekAE4NzCE8

**Proof/evidence**
CkpYRZbTPuhWrgi7BV2VA6mL5p33tjSz6UDsSTTPD3YAHmDbqzDdz

**Comment by nerdvibe** [comment]
Added on https://github.com/nerdvibe/mina-addresses-blacklist/commit/d742a12b1fa1b17e8191ee3ad9d275adfebd6443
